//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartialTrustInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartialTrustInstaller.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainWindow_Cancel_Close {
            get {
                return ResourceManager.GetString("MainWindow_Cancel_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainWindow_CancelButtonText {
            get {
                return ResourceManager.GetString("MainWindow_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string MainWindow_MainWindow_B {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string MainWindow_MainWindow_KB {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MainWindow_MainWindow_MB {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive unpacking....
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Archive_unpacking___ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Archive_unpacking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download version {0} of {1}....
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Download_version__0__of__1 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Download_version__0__of__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading manifest....
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Downloading_manifest {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Downloading_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Failed_to_create_directory_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Failed_to_create_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully downloaded!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_File_successfully_downloaded {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_File_successfully_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Finish {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest successfully downloaded!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Manifest_successfully_downloaded {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Manifest_successfully_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program installation completed successfully!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Program_installation_completed_successfully_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Program_installation_completed_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is corrupted!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_The_file_is_corrupted {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_The_file_is_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already installed.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_The_program_is_already_installed {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_The_program_is_already_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already installed on your computer. Would you like to replace it with version {0} of {1}?.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_The_program_is_already_installed_on_your_computer__Would_you_like_to_replace_it_with_version__0__of__1__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_The_program_is_already_installed_on_your_computer__" +
                        "Would_you_like_to_replace_it_with_version__0__of__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Unable_to_download_file {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Unable_to_download_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download manifest!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Unable_to_download_manifest {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Unable_to_download_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove the previous installation!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Unable_to_remove_the_previous_installation_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Unable_to_remove_the_previous_installation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unzip the archive!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Unable_to_unzip_the_archive_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Unable_to_unzip_the_archive_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong digital signature of the manifest!.
        /// </summary>
        public static string MainWindow_MainWindowOnLoaded_Wrong_digital_signature_of_the_manifest {
            get {
                return ResourceManager.GetString("MainWindow_MainWindowOnLoaded_Wrong_digital_signature_of_the_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebMoney Business Tools Setup.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
