//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMoney.Services.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMoney.Services.Contracts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse does not match WMID.
        /// </summary>
        internal static string AlienPurseException_Caption_Purse_does_not_match_WMID {
            get {
                return ResourceManager.GetString("AlienPurseException_Caption_Purse_does_not_match_WMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same identifier already registered.
        /// </summary>
        internal static string DuplicateIdentifierException_Caption_Same_identifier_already_registered {
            get {
                return ResourceManager.GetString("DuplicateIdentifierException_Caption_Same_identifier_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMID already registered.
        /// </summary>
        internal static string DuplicateRegistrationException_Caption_WMID_already_registered {
            get {
                return ResourceManager.GetString("DuplicateRegistrationException_Caption_WMID_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request rejected by WebMoney.
        /// </summary>
        internal static string ExternalBusinessException_Caption_Request_rejected_by_WebMoney {
            get {
                return ResourceManager.GetString("ExternalBusinessException_Caption_Request_rejected_by_WebMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys file not found.
        /// </summary>
        internal static string KeyNotFoundException_Caption_Keys_file_not_found {
            get {
                return ResourceManager.GetString("KeyNotFoundException_Caption_Keys_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse not found.
        /// </summary>
        internal static string PurseNotFoundException_Caption_Purse_not_found {
            get {
                return ResourceManager.GetString("PurseNotFoundException_Caption_Purse_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file format.
        /// </summary>
        internal static string WrongFileFormatException_Caption_Wrong_file_format {
            get {
                return ResourceManager.GetString("WrongFileFormatException_Caption_Wrong_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string WrongPasswordException_Caption_Wrong_password {
            get {
                return ResourceManager.GetString("WrongPasswordException_Caption_Wrong_password", resourceCulture);
            }
        }
    }
}
