//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMBusinessTools.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMBusinessTools.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff36\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f36\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0302020204030204}Calibri Light;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Cali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMID#{0} already registered in the program!.
        /// </summary>
        internal static string AddIdentifierFormProvider_GetForm_WMID__0__already_registered_in_the_program {
            get {
                return ResourceManager.GetString("AddIdentifierFormProvider_GetForm_WMID__0__already_registered_in_the_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CreateContractFormProvider_GetForm_Error {
            get {
                return ResourceManager.GetString("CreateContractFormProvider_GetForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers is in the wrong format. Please, use comma, semicolon, space or newline as separator..
        /// </summary>
        internal static string CreateContractFormProvider_GetForm_List_of_identifiers_is_in_the_wrong_format {
            get {
                return ResourceManager.GetString("CreateContractFormProvider_GetForm_List_of_identifiers_is_in_the_wrong_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh the list of purses or add add at least one purse manually..
        /// </summary>
        internal static string CreateTrustFormProvider_GetForm_Please_refresh_the_list_of_purses_or_add_it_manually {
            get {
                return ResourceManager.GetString("CreateTrustFormProvider_GetForm_Please_refresh_the_list_of_purses_or_add_it_manua" +
                        "lly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purses list is empty.
        /// </summary>
        internal static string CreateTrustFormProvider_GetForm_Purses_list_is_empty {
            get {
                return ResourceManager.GetString("CreateTrustFormProvider_GetForm_Purses_list_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable connect to database!.
        /// </summary>
        internal static string DbSettingsService_CheckConnectionSettings_Unable_connect_to_database_ {
            get {
                return ResourceManager.GetString("DbSettingsService_CheckConnectionSettings_Unable_connect_to_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        internal static string ErrorFormDisplayHelper_GetErrorAction_Operation_failed {
            get {
                return ResourceManager.GetString("ErrorFormDisplayHelper_GetErrorAction_Operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string ErrorFormDisplayHelper_GetErrorAction_Unexpected_error {
            get {
                return ResourceManager.GetString("ErrorFormDisplayHelper_GetErrorAction_Unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse {0} not found!.
        /// </summary>
        internal static string FindIdentifierFormProvider_GetForm_Purse__0__not_found_ {
            get {
                return ResourceManager.GetString("FindIdentifierFormProvider_GetForm_Purse__0__not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notify {
            get {
                return ResourceManager.GetStream("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream payment {
            get {
                return ResourceManager.GetStream("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream paymentp {
            get {
                return ResourceManager.GetStream("paymentp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string ProgressForm_mBackgroundWorker_RunWorkerCompleted_Connection_error {
            get {
                return ResourceManager.GetString("ProgressForm_mBackgroundWorker_RunWorkerCompleted_Connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the database with connection string &apos;{0}&apos;!.
        /// </summary>
        internal static string ProgressForm_mBackgroundWorker_RunWorkerCompleted_Could_not_connect_to_the_database_with_connection_string___0___ {
            get {
                return ResourceManager.GetString("ProgressForm_mBackgroundWorker_RunWorkerCompleted_Could_not_connect_to_the_databa" +
                        "se_with_connection_string___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMID#{0} already registered!.
        /// </summary>
        internal static string RegistrationFormProvider_Step1_WMID__0__already_registered_ {
            get {
                return ResourceManager.GetString("RegistrationFormProvider_Step1_WMID__0__already_registered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password or WMID for kwm-file!.
        /// </summary>
        internal static string RegistrationFormProvider_Step1_Wrong_password_or_WMID_for_kwm_file_ {
            get {
                return ResourceManager.GetString("RegistrationFormProvider_Step1_Wrong_password_or_WMID_for_kwm_file_", resourceCulture);
            }
        }
    }
}
