//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMoney.Services.SmsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.SmsSenderSvcSoap")]
    public interface SmsSenderSvcSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSingleSMS", ReplyAction="*")]
        WebMoney.Services.SmsServiceReference.SendSingleSMSResponse SendSingleSMS(WebMoney.Services.SmsServiceReference.SendSingleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSingleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.SendSingleSMSResponse> SendSingleSMSAsync(WebMoney.Services.SmsServiceReference.SendSingleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatus", ReplyAction="*")]
        WebMoney.Services.SmsServiceReference.GetSMSStatusResponse GetSMSStatus(WebMoney.Services.SmsServiceReference.GetSMSStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetSMSStatusResponse> GetSMSStatusAsync(WebMoney.Services.SmsServiceReference.GetSMSStatusRequest request);
        
        // CODEGEN: Generating message contract since element name phoneNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCost", ReplyAction="*")]
        WebMoney.Services.SmsServiceReference.GetMessageCostResponse GetMessageCost(WebMoney.Services.SmsServiceReference.GetMessageCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCost", ReplyAction="*")]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetMessageCostResponse> GetMessageCostAsync(WebMoney.Services.SmsServiceReference.GetMessageCostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingleSMS", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.SendSingleSMSRequestBody Body;
        
        public SendSingleSMSRequest() {
        }
        
        public SendSingleSMSRequest(WebMoney.Services.SmsServiceReference.SendSingleSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSingleSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool transliterate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string wmid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderPursue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool internalpayment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string requestSign;
        
        public SendSingleSMSRequestBody() {
        }
        
        public SendSingleSMSRequestBody(string phoneNumber, string messageText, bool transliterate, string wmid, string senderPursue, string dateTime, bool internalpayment, string requestSign) {
            this.phoneNumber = phoneNumber;
            this.messageText = messageText;
            this.transliterate = transliterate;
            this.wmid = wmid;
            this.senderPursue = senderPursue;
            this.dateTime = dateTime;
            this.internalpayment = internalpayment;
            this.requestSign = requestSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingleSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.SendSingleSMSResponseBody Body;
        
        public SendSingleSMSResponse() {
        }
        
        public SendSingleSMSResponse(WebMoney.Services.SmsServiceReference.SendSingleSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSingleSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSingleSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int smsID;
        
        public SendSingleSMSResponseBody() {
        }
        
        public SendSingleSMSResponseBody(int SendSingleSMSResult, int smsID) {
            this.SendSingleSMSResult = SendSingleSMSResult;
            this.smsID = smsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSStatus", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.GetSMSStatusRequestBody Body;
        
        public GetSMSStatusRequest() {
        }
        
        public GetSMSStatusRequest(WebMoney.Services.SmsServiceReference.GetSMSStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSMSStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string wmid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string requestSign;
        
        public GetSMSStatusRequestBody() {
        }
        
        public GetSMSStatusRequestBody(int smsID, string dateTime, string wmid, string requestSign) {
            this.smsID = smsID;
            this.dateTime = dateTime;
            this.wmid = wmid;
            this.requestSign = requestSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.GetSMSStatusResponseBody Body;
        
        public GetSMSStatusResponse() {
        }
        
        public GetSMSStatusResponse(WebMoney.Services.SmsServiceReference.GetSMSStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSMSStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetSMSStatusResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int status;
        
        public GetSMSStatusResponseBody() {
        }
        
        public GetSMSStatusResponseBody(int GetSMSStatusResult, int status) {
            this.GetSMSStatusResult = GetSMSStatusResult;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageCost", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.GetMessageCostRequestBody Body;
        
        public GetMessageCostRequest() {
        }
        
        public GetMessageCostRequest(WebMoney.Services.SmsServiceReference.GetMessageCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstPurseLetter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int packageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int profileID;
        
        public GetMessageCostRequestBody() {
        }
        
        public GetMessageCostRequestBody(string phoneNumber, string firstPurseLetter, int packageSize, int profileID) {
            this.phoneNumber = phoneNumber;
            this.firstPurseLetter = firstPurseLetter;
            this.packageSize = packageSize;
            this.profileID = profileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageCostResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebMoney.Services.SmsServiceReference.GetMessageCostResponseBody Body;
        
        public GetMessageCostResponse() {
        }
        
        public GetMessageCostResponse(WebMoney.Services.SmsServiceReference.GetMessageCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal GetMessageCostResult;
        
        public GetMessageCostResponseBody() {
        }
        
        public GetMessageCostResponseBody(decimal GetMessageCostResult) {
            this.GetMessageCostResult = GetMessageCostResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSenderSvcSoapChannel : WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSenderSvcSoapClient : System.ServiceModel.ClientBase<WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap>, WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap {
        
        public SmsSenderSvcSoapClient() {
        }
        
        public SmsSenderSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSenderSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSenderSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSenderSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebMoney.Services.SmsServiceReference.SendSingleSMSResponse WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.SendSingleSMS(WebMoney.Services.SmsServiceReference.SendSingleSMSRequest request) {
            return base.Channel.SendSingleSMS(request);
        }
        
        public int SendSingleSMS(string phoneNumber, string messageText, bool transliterate, string wmid, string senderPursue, string dateTime, bool internalpayment, string requestSign, out int smsID) {
            WebMoney.Services.SmsServiceReference.SendSingleSMSRequest inValue = new WebMoney.Services.SmsServiceReference.SendSingleSMSRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.SendSingleSMSRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.messageText = messageText;
            inValue.Body.transliterate = transliterate;
            inValue.Body.wmid = wmid;
            inValue.Body.senderPursue = senderPursue;
            inValue.Body.dateTime = dateTime;
            inValue.Body.internalpayment = internalpayment;
            inValue.Body.requestSign = requestSign;
            WebMoney.Services.SmsServiceReference.SendSingleSMSResponse retVal = ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).SendSingleSMS(inValue);
            smsID = retVal.Body.smsID;
            return retVal.Body.SendSingleSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.SendSingleSMSResponse> WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.SendSingleSMSAsync(WebMoney.Services.SmsServiceReference.SendSingleSMSRequest request) {
            return base.Channel.SendSingleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.SendSingleSMSResponse> SendSingleSMSAsync(string phoneNumber, string messageText, bool transliterate, string wmid, string senderPursue, string dateTime, bool internalpayment, string requestSign) {
            WebMoney.Services.SmsServiceReference.SendSingleSMSRequest inValue = new WebMoney.Services.SmsServiceReference.SendSingleSMSRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.SendSingleSMSRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.messageText = messageText;
            inValue.Body.transliterate = transliterate;
            inValue.Body.wmid = wmid;
            inValue.Body.senderPursue = senderPursue;
            inValue.Body.dateTime = dateTime;
            inValue.Body.internalpayment = internalpayment;
            inValue.Body.requestSign = requestSign;
            return ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).SendSingleSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebMoney.Services.SmsServiceReference.GetSMSStatusResponse WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.GetSMSStatus(WebMoney.Services.SmsServiceReference.GetSMSStatusRequest request) {
            return base.Channel.GetSMSStatus(request);
        }
        
        public int GetSMSStatus(int smsID, string dateTime, string wmid, string requestSign, out int status) {
            WebMoney.Services.SmsServiceReference.GetSMSStatusRequest inValue = new WebMoney.Services.SmsServiceReference.GetSMSStatusRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.GetSMSStatusRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.dateTime = dateTime;
            inValue.Body.wmid = wmid;
            inValue.Body.requestSign = requestSign;
            WebMoney.Services.SmsServiceReference.GetSMSStatusResponse retVal = ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).GetSMSStatus(inValue);
            status = retVal.Body.status;
            return retVal.Body.GetSMSStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetSMSStatusResponse> WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.GetSMSStatusAsync(WebMoney.Services.SmsServiceReference.GetSMSStatusRequest request) {
            return base.Channel.GetSMSStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetSMSStatusResponse> GetSMSStatusAsync(int smsID, string dateTime, string wmid, string requestSign) {
            WebMoney.Services.SmsServiceReference.GetSMSStatusRequest inValue = new WebMoney.Services.SmsServiceReference.GetSMSStatusRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.GetSMSStatusRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.dateTime = dateTime;
            inValue.Body.wmid = wmid;
            inValue.Body.requestSign = requestSign;
            return ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).GetSMSStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebMoney.Services.SmsServiceReference.GetMessageCostResponse WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.GetMessageCost(WebMoney.Services.SmsServiceReference.GetMessageCostRequest request) {
            return base.Channel.GetMessageCost(request);
        }
        
        public decimal GetMessageCost(string phoneNumber, string firstPurseLetter, int packageSize, int profileID) {
            WebMoney.Services.SmsServiceReference.GetMessageCostRequest inValue = new WebMoney.Services.SmsServiceReference.GetMessageCostRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.GetMessageCostRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.firstPurseLetter = firstPurseLetter;
            inValue.Body.packageSize = packageSize;
            inValue.Body.profileID = profileID;
            WebMoney.Services.SmsServiceReference.GetMessageCostResponse retVal = ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).GetMessageCost(inValue);
            return retVal.Body.GetMessageCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetMessageCostResponse> WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap.GetMessageCostAsync(WebMoney.Services.SmsServiceReference.GetMessageCostRequest request) {
            return base.Channel.GetMessageCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebMoney.Services.SmsServiceReference.GetMessageCostResponse> GetMessageCostAsync(string phoneNumber, string firstPurseLetter, int packageSize, int profileID) {
            WebMoney.Services.SmsServiceReference.GetMessageCostRequest inValue = new WebMoney.Services.SmsServiceReference.GetMessageCostRequest();
            inValue.Body = new WebMoney.Services.SmsServiceReference.GetMessageCostRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.firstPurseLetter = firstPurseLetter;
            inValue.Body.packageSize = packageSize;
            inValue.Body.profileID = profileID;
            return ((WebMoney.Services.SmsServiceReference.SmsSenderSvcSoap)(this)).GetMessageCostAsync(inValue);
        }
    }
}
